apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: application
serialPipeline:
  stages:
    - targetId: staging-app
      profiles:
        - staging-app
      strategy:
        standard:
          predeploy:
            actions: ["pre-deployhook"]
          postdeploy:
            actions: ["post-staging-deployhook"]
    - targetId: production-app
      profiles:
        - production-app
      strategy:
        standard:
          predeploy:
            actions: ["pre-deployhook"]
          postdeploy:
            actions: ["post-production-deployhook"]
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
 name: staging-app
description: deploy application
requireApproval: false
run:
  location: projects/pupupu-cafe/locations/asia-northeast1
executionConfigs:
  - usages:
      - RENDER
      - PREDEPLOY
      - DEPLOY
      - VERIFY
      - POSTDEPLOY
    executionTimeout: 7200s
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
 name: production-app
description: deploy application
requireApproval: true
run:
  location: projects/pupupu-cafe/locations/asia-northeast1
executionConfigs:
  - usages:
      - RENDER
      - PREDEPLOY
      - DEPLOY
      - VERIFY
      - POSTDEPLOY
    executionTimeout: 7200s
