apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: app
profiles:
  - name: staging-app
    manifests:
      rawYaml:
        - resources/staging/run_service.yaml
    deploy:
      cloudrun:
        projectid: pupupu-cafe
        region: asia-northeast1
  - name: production-app
    manifests:
      rawYaml:
        - resources/production/run_service.yaml
    deploy:
      cloudrun:
        projectid: pupupu-cafe
        region: asia-northeast1
customActions:
  - name: pre-deployhook
    containers:
      - name: gcloud-build
        image: gcr.io/google.com/cloudsdktool/google-cloud-cli:slim
        command:
          - "bash"
          - "-c"
          - |
            gsutil cp gs://d5275a8d76004a658ba8e735e44e2818_clouddeploy/source/${CLOUD_DEPLOY_RELEASE}.tar.gz .
            tar xzvf ${CLOUD_DEPLOY_RELEASE}.tar.gz
            gcloud builds submit --config ./hooks/setup_cloudbuild.yaml --region asia-northeast1 --no-source
  - name: post-staging-deployhook
    containers:
      - name: run-cloud-build-for-staging
        image: gcr.io/google.com/cloudsdktool/google-cloud-cli:slim
        command:
          - "bash"
          - "-c"
          - |
            gsutil cp gs://d5275a8d76004a658ba8e735e44e2818_clouddeploy/source/${CLOUD_DEPLOY_RELEASE}.tar.gz .
            tar xzvf ${CLOUD_DEPLOY_RELEASE}.tar.gz
            gcloud app deploy resources/staging/app.yaml --promote --stop-previous-version --version=${CLOUD_DEPLOY_RELEASE} --quiet --image-url=asia.gcr.io/pupupu-cafe/hello
  - name: post-production-deployhook
    containers:
      - name: run-cloud-build-for-production
        image: gcr.io/google.com/cloudsdktool/google-cloud-cli:slim
        command:
          - "bash"
          - "-c"
          - |
            gsutil cp gs://d5275a8d76004a658ba8e735e44e2818_clouddeploy/source/${CLOUD_DEPLOY_RELEASE}.tar.gz .
            tar xzvf ${CLOUD_DEPLOY_RELEASE}.tar.gz
            gcloud app deploy resources/production/app.yaml --promote --stop-previous-version --version=${CLOUD_DEPLOY_RELEASE} --quiet --image-url=asia.gcr.io/pupupu-cafe/hello
