apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: app
build:
  local:
    push: true
  artifacts:
    - image: asia.gcr.io/pupupu-cafe/hello
      docker:
        dockerfile: ./Dockerfile
profiles:
  - name: staging-app
    manifests:
      rawYaml:
        - resources/stg-service.yaml
    deploy:
      cloudrun:
        projectid: pupupu-cafe
        region: asia-northeast1
        hooks:
          before:
            - command: ["sh", "-c", "echo pre-deploy host hook running on $(hostname)!"]
          after:
            - command: ["sh", "-c", "echo post-deploy host hook running on $(hostname)!"]
  - name: production-app
    manifests:
      rawYaml:
        - resources/prod-service.yaml
    deploy:
      cloudrun:
        projectid: moonstruckdrops
        region: asia-northeast1
        hooks:
          before:
            - command: ["sh", "-c", "echo pre-deploy host hook running on $(hostname)!"]
          after:
            - command: ["sh", "-c", "echo post-deploy host hook running on $(hostname)!"]
