apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: serverless
profiles:
  - name: development
    manifests:
      rawYaml:
        - resources/development/run_service.yaml
    deploy:
      cloudrun:
        projectid: pupupu-cafe
        region: asia-northeast1
  - name: staging
    manifests:
      rawYaml:
        - resources/staging/run_service.yaml
    deploy:
      cloudrun:
        projectid: pupupu-cafe
        region: asia-northeast1
  - name: production
    manifests:
      rawYaml:
        - resources/production/run_service.yaml
    deploy:
      cloudrun:
        projectid: pupupu-cafe
        region: asia-northeast1
customActions:
  - name: setup
    containers:
      - name: setup
        image: gcr.io/google.com/cloudsdktool/google-cloud-cli:slim
        command:
          - "bash"
          - "-c"
          - |
            gsutil cp gs://${CLOUD_DEPLOY_DELIVERY_PIPELINE}/${CLOUD_DEPLOY_RELEASE}.tar.gz .
            tar xzvf ${CLOUD_DEPLOY_RELEASE}.tar.gz
            gcloud builds submit --config ./hooks/setup_cloudbuild.yaml --region asia-northeast1 --no-source
  - name: post-deploy
    containers:
      - name: deploy-appengine
        image: gcr.io/google.com/cloudsdktool/google-cloud-cli:slim
        command:
          - "bash"
          - "-c"
          - |
            gsutil cp gs://${CLOUD_DEPLOY_DELIVERY_PIPELINE}/${CLOUD_DEPLOY_RELEASE}.tar.gz .
            tar xzvf ${CLOUD_DEPLOY_RELEASE}.tar.gz
            gcloud app deploy resources/${CLOUD_DEPLOY_TARGET}/app.yaml --promote --stop-previous-version --version=${CLOUD_DEPLOY_RELEASE} --quiet --image-url=asia.gcr.io/pupupu-cafe/hello
  - name: teardown
    containers:
      - name: teardown
        image: gcr.io/google.com/cloudsdktool/google-cloud-cli:slim
        command:
          - "bash"
          - "-c"
          - |
            gsutil cp gs://${CLOUD_DEPLOY_DELIVERY_PIPELINE}/${CLOUD_DEPLOY_RELEASE}.tar.gz .
            tar xzvf ${CLOUD_DEPLOY_RELEASE}.tar.gz
            gcloud builds submit --config ./hooks/teardown_cloudbuild.yaml --region asia-northeast1 --no-source
