runtime: custom
env: flex
service: staging

network:
  name: ${CLOUD_DEPLOY_PROJECT}
  subnetwork_name: ${CLOUD_DEPLOY_PROJECT}
  instance_tag: staging

resources:
  cpu: 2
  memory_gb: 7.6
  disk_size_gb: 10

manual_scaling:
  instances: 1
